version: "3"

services:
  keycloak: quay.io/keycloak/keycloak:21.1
  command: start-dev
  ports:
    - "8080:8080"
  environment:
    - KEYCLOAK_USER=admin
    - KEYCLOAK_PASSWORD=admin
    - DB_VENDOR=H2
